import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { EmailInput } from '../components/emailInput';
import { Input,Textarea,Button} from '@nextui-org/react';
import { SendIcon } from '../components/sendIcon';


export default function Home() {
  const [arrEmails,setArrEmails] = useState([])
  const [email,setEmail] = useState('')
  const [subject,setSubject] = useState('')
  const [messageContent,setMessageContent] = useState('')

  const handleSubmit = async (e) => {
    console.log(arrEmails)
    e.preventDefault()
    await axios.post('http://localhost:4000/api/sendmails',{
      subject,
      emails : arrEmails,
      msg_content : messageContent
    })
  }

  const handleAddEmail = (e) => {
    e.preventDefault()
    if(arrEmails.includes(email)){
      console.log('email already in')
    } else {
      const newArrEmails = [...arrEmails,email]
      setArrEmails(newArrEmails)
      setEmail('')
    }
    
  }

  const handleDeleteEmail = (e) => {
    arrEmails = arrEmails.filter(item => item !== e)
    setArrEmails(arrEmails)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.formContainer}>
      <form onSubmit={handleAddEmail}>
      <EmailInput setEmail={setEmail} email={email}/>
      </form>
      <form className={styles.messageForm} onSubmit={handleSubmit}>
      <Input
        clearable
        underlined
        labelPlaceholder="Subject"
        onChange={(e)=> setSubject(e.target.value)}
      />
         <Textarea
          underlined
          color="primary"
          labelPlaceholder="Message"
          onChange={(e)=> setMessageContent(e.target.value)}
        />
        <Button 
        type='submit'
        auto
        color='primary'
        icon={<SendIcon fill='currentColor' filled/>}/>
      </form>
      {arrEmails ? arrEmails.map((e,i)=> <p onClick={()=>handleDeleteEmail(e) } key={i}>{e}</p>) : null}
      </div>
    </div>
  )
}